<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="15" passed="11">
  <reporter-output>
  </reporter-output>
  <suite name="QuaMinds-FrontEndTests" duration-ms="52193" started-at="2019-11-28T20:24:08Z" finished-at="2019-11-28T20:25:00Z">
    <groups>
    </groups>
    <test name="MLTests-Chrome" duration-ms="26039" started-at="2019-11-28T20:24:08Z" finished-at="2019-11-28T20:24:34Z">
      <class name="FrontEndTests.FE_Tests">
        <test-method status="PASS" signature="setUpTests(java.lang.String)[pri:0, instance:FrontEndTests.FE_Tests@6e0e048a]" name="setUpTests" is-config="true" duration-ms="3671" started-at="2019-11-28T20:24:08Z" finished-at="2019-11-28T20:24:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTests -->
        <test-method status="FAIL" signature="ejercicio2()[pri:0, instance:FrontEndTests.FE_Tests@6e0e048a]" name="ejercicio2" duration-ms="6224" started-at="2019-11-28T20:24:11Z" description="Verify Free Shipping Bar" finished-at="2019-11-28T20:24:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at FrontEndTests.FE_Tests.ejercicio2(FE_Tests.java:208)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ejercicio2 -->
        <test-method status="PASS" signature="verifyCategoryClimatizacion()[pri:0, instance:FrontEndTests.FE_Tests@6e0e048a]" name="verifyCategoryClimatizacion" duration-ms="3771" started-at="2019-11-28T20:24:17Z" description="Verificar categoria - Climatizacion" finished-at="2019-11-28T20:24:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCategoryClimatizacion -->
        <test-method status="FAIL" signature="verifyPrices()[pri:0, instance:FrontEndTests.FE_Tests@6e0e048a]" name="verifyPrices" duration-ms="4862" started-at="2019-11-28T20:24:21Z" description="Verificar el mayor y el menor precio de una categoria" finished-at="2019-11-28T20:24:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at FrontEndTests.FE_Tests.verifyPrices(FE_Tests.java:157)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPrices -->
        <test-method status="PASS" signature="verifySmartCellsGrid()[pri:0, instance:FrontEndTests.FE_Tests@6e0e048a]" name="verifySmartCellsGrid" duration-ms="6745" started-at="2019-11-28T20:24:26Z" description="Verificar la grilla de Celulares y Smartphones" finished-at="2019-11-28T20:24:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySmartCellsGrid -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:FrontEndTests.FE_Tests@6e0e048a]" name="closeDriver" is-config="true" duration-ms="762" started-at="2019-11-28T20:24:33Z" finished-at="2019-11-28T20:24:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- FrontEndTests.FE_Tests -->
    </test> <!-- MLTests-Chrome -->
    <test name="MLTests-Firefox" duration-ms="26118" started-at="2019-11-28T20:24:34Z" finished-at="2019-11-28T20:25:00Z">
      <class name="FrontEndTests.FE_Tests">
        <test-method status="PASS" signature="setUpTests(java.lang.String)[pri:0, instance:FrontEndTests.FE_Tests@5c5a1b69]" name="setUpTests" is-config="true" duration-ms="3978" started-at="2019-11-28T20:24:34Z" finished-at="2019-11-28T20:24:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTests -->
        <test-method status="PASS" signature="ejercicio2()[pri:0, instance:FrontEndTests.FE_Tests@5c5a1b69]" name="ejercicio2" duration-ms="6413" started-at="2019-11-28T20:24:38Z" description="Verify Free Shipping Bar" finished-at="2019-11-28T20:24:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ejercicio2 -->
        <test-method status="PASS" signature="verifyCategoryClimatizacion()[pri:0, instance:FrontEndTests.FE_Tests@5c5a1b69]" name="verifyCategoryClimatizacion" duration-ms="3545" started-at="2019-11-28T20:24:44Z" description="Verificar categoria - Climatizacion" finished-at="2019-11-28T20:24:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCategoryClimatizacion -->
        <test-method status="FAIL" signature="verifyPrices()[pri:0, instance:FrontEndTests.FE_Tests@5c5a1b69]" name="verifyPrices" duration-ms="4886" started-at="2019-11-28T20:24:48Z" description="Verificar el mayor y el menor precio de una categoria" finished-at="2019-11-28T20:24:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at FrontEndTests.FE_Tests.verifyPrices(FE_Tests.java:157)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPrices -->
        <test-method status="PASS" signature="verifySmartCellsGrid()[pri:0, instance:FrontEndTests.FE_Tests@5c5a1b69]" name="verifySmartCellsGrid" duration-ms="6035" started-at="2019-11-28T20:24:52Z" description="Verificar la grilla de Celulares y Smartphones" finished-at="2019-11-28T20:24:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySmartCellsGrid -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:FrontEndTests.FE_Tests@5c5a1b69]" name="closeDriver" is-config="true" duration-ms="1256" started-at="2019-11-28T20:24:59Z" finished-at="2019-11-28T20:25:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- FrontEndTests.FE_Tests -->
    </test> <!-- MLTests-Firefox -->
  </suite> <!-- QuaMinds-FrontEndTests -->
  <suite name="QuaMinds-BackEndTests" duration-ms="7134" started-at="2019-11-28T20:24:00Z" finished-at="2019-11-28T20:24:08Z">
    <groups>
    </groups>
    <test name="MLTests" duration-ms="7134" started-at="2019-11-28T20:24:00Z" finished-at="2019-11-28T20:24:08Z">
      <class name="BackEndTests.BE_Tests">
        <test-method status="PASS" signature="setUpTests()[pri:0, instance:BackEndTests.BE_Tests@4e1d422d]" name="setUpTests" is-config="true" duration-ms="10" started-at="2019-11-28T20:24:00Z" finished-at="2019-11-28T20:24:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTests -->
        <test-method status="PASS" signature="verifyCurrency()[pri:0, instance:BackEndTests.BE_Tests@4e1d422d]" name="verifyCurrency" duration-ms="3013" started-at="2019-11-28T20:24:00Z" description="Verifica tipo de moneda para el pago" finished-at="2019-11-28T20:24:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCurrency -->
        <test-method status="PASS" signature="verifyFreeShipping()[pri:0, instance:BackEndTests.BE_Tests@4e1d422d]" name="verifyFreeShipping" duration-ms="911" started-at="2019-11-28T20:24:03Z" description="Verifica envio grais" finished-at="2019-11-28T20:24:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFreeShipping -->
        <test-method status="PASS" signature="verifyMercadoPago()[pri:0, instance:BackEndTests.BE_Tests@4e1d422d]" name="verifyMercadoPago" duration-ms="673" started-at="2019-11-28T20:24:04Z" description="Verifica si el producto acepta mercado pago" finished-at="2019-11-28T20:24:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMercadoPago -->
        <test-method status="PASS" signature="verifyProductPrice()[pri:0, instance:BackEndTests.BE_Tests@4e1d422d]" name="verifyProductPrice" duration-ms="686" started-at="2019-11-28T20:24:05Z" description="Verifica el precio de un producto" finished-at="2019-11-28T20:24:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductPrice -->
        <test-method status="PASS" signature="verifyProductTitle()[pri:0, instance:BackEndTests.BE_Tests@4e1d422d]" name="verifyProductTitle" duration-ms="769" started-at="2019-11-28T20:24:06Z" description="Verifica el titulo de un producto" finished-at="2019-11-28T20:24:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductTitle -->
        <test-method status="FAIL" signature="verifyProductsPaging()[pri:0, instance:BackEndTests.BE_Tests@4e1d422d]" name="verifyProductsPaging" duration-ms="581" started-at="2019-11-28T20:24:06Z" description="Verifica productos por pagina" finished-at="2019-11-28T20:24:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at BackEndTests.BE_Tests.verifyProductsPaging(BE_Tests.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductsPaging -->
        <test-method status="PASS" signature="verifyProductsTotal()[pri:0, instance:BackEndTests.BE_Tests@4e1d422d]" name="verifyProductsTotal" duration-ms="477" started-at="2019-11-28T20:24:07Z" description="Verifica total de productos" finished-at="2019-11-28T20:24:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductsTotal -->
      </class> <!-- BackEndTests.BE_Tests -->
    </test> <!-- MLTests -->
  </suite> <!-- QuaMinds-BackEndTests -->
  <suite name="QuaMinds-AutomationTests" duration-ms="0" started-at="2019-11-28T20:25:00Z" finished-at="2019-11-28T20:25:00Z">
    <groups>
    </groups>
  </suite> <!-- QuaMinds-AutomationTests -->
</testng-results>
